# Generated by Django 4.0.3 on 2022-04-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=32)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('total', models.IntegerField()),
                ('use', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ControlPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=32)),
                ('person', models.IntegerField()),
                ('unusual', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IotEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('time', models.CharField(max_length=64)),
                ('place', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PersonNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentNum', models.IntegerField()),
                ('TeacherNum', models.IntegerField()),
                ('WorkerNum', models.IntegerField()),
                ('Freshman', models.IntegerField()),
                ('Sophomore', models.IntegerField()),
                ('Junior', models.IntegerField()),
                ('Senior', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
